### ISSUE TITLE
nais cli 2.0

### ISSUE THREAD

**Issue by frodesundby** [nais/cli#108]
Vi har jo et CLI i dag, men det gjør jo ikke så alt for mye nyttig... enda.
Her er det potensiale for å gjøre mye moro.

Hva om nais CLI er en slags kjernekomponent i hverdagen til en nais-utvikler?
Om vi ser for oss at du som ny utvikler skriver `nais up`, og alt som er nais installeres automatisk for deg:
- naisdevice
- kubeconfigs hentes
- gloud installeres

Når du så har fått alt som er nais får du så mulighet til å bruke dette CLI'et for å navigere alle naistjenester som er tilgjengelige:
- logger
- metrikker
- app-info
- deploy
- doktor
- databasekobling
- manifestgenerering
- osv.

**Comment by frodesundby** [comment]
Co-sign har egentlig en veldig fin struktur for å legge til nye kommandoer, sier @tommytroen 
Anbefaler å hente inspirasjon fra dette når/om man går i gang med denne oppgaven.

**Comment by frodesundby** [comment]
Før vi går i gang med denne oppgaven bør vi gjøre litt grunnarbeide for å finne ut i hvor stor grad cli'er er i bruk i dag.

**Comment by Kyrremann** [comment]
Så vidt jeg vet er cli-et mye i brukt for Kafka og Postgres.

**Comment by mortenlj** [comment]
Med Console så er kanskje ikke dette issuet så interessant lenger?

**Comment by ybelMekk** [comment]
tenker vi kan close denne så lenge
