### ISSUE TITLE
En idé: Installere med brew på Linux også, istedenfor apt/deb/PPA?

### ISSUE THREAD

**Issue by ahusby** [nais/cli#11]
Ikke den viktigste saken i verden, men ser på https://doc.nais.io/cli/install/ at anbefalt installasjonsbetode for Mac er med brew og for Linux med apt-kommandoen og et PPA. Brew fungerer fint på Linux også. Er det kanskje lettere å distribuere via Brew for Linux, akkurat som for Mac?

**Comment by Sechmann** [comment]
Ting jeg ikke liker med brew på linux:
* Man må installere det
* Man må selv holde styr på hva en "pakke" oppretter av filer
* Signering av pakker
* Dependencies

Det vi kunne gjort er å lage et linuxbrew script i tillegg, som wrapper ppa varianten - men vet ikke om det er verdt bryet.

PPA instruksjonene våre kunne også vært forenklet, vi har veldig komplisert oppsett i forhold til hva som egentlig trengs fordi PPA repoet vårt ikke er helt riktig satt opp.

Eneste grunnen til at vi bruker det for Mac er fordi det ikke finnes noen offisielle alternativer. 
På skikkelige OS foretrekker jeg de offisielle verktøyene.

**Comment by mortenlj** [comment]
For nais-cli så er det faktisk mulig å bruke brew, men som @Sechmann sier er det grunner til å anbefale PPA'en.

**Comment by ahusby** [comment]
Okay. Da har noen som kan mer enn meg tenkt på det, så da kan denne issuen godt lukkes for min del.
