### ISSUE TITLE
postgres: pgpass is created in the wrong location on Windows

### ISSUE THREAD

**Issue by ThomasKasene** [nais/cli#169]
There's a discussion on [Slack](https://nav-it.slack.com/archives/C5KUST8N6/p1681371891568219) about his for more context and workarounds, but essentially, the location and filename for the pgpass file are different on Windows than they are on Linux and Mac, and the CLI doesn't take this into account when it generates (or updates) it.

An extract from the [PostgreSQL documentation](https://www.postgresql.org/docs/current/libpq-pgpass.html):
> The file `.pgpass` in a user's home directory can contain passwords to be used if the connection requires a password (and no password has been specified otherwise). On Microsoft Windows the file is named `%APPDATA%\postgresql\pgpass.conf` (where `%APPDATA%` refers to the Application Data subdirectory in the user's profile). Alternatively, the password file to use can be specified using the connection parameter [passfile](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-PASSFILE) or the environment variable `PGPASSFILE`.

Now of course, we _could_ use those workarounds, but I submit that a tool that aims to reduce friction should take care of this for us 😄

**Comment by Kyrremann** [comment]
Denne er løst med at man ikke trenger å bruke en pgpass fil lengre (v1.20230525140036), så lukker denne.
