### ISSUE TITLE
postgres: støtte rotasjon av credentials

### ISSUE THREAD

**Issue by androa** [nais/cli#191]
[Dokumentasjonen og NAIS](https://docs.nais.io/persistence/postgres/#workaround-for-password-synchronization-issues) burde kunne bakes inn i nais cli. Begge deler er vel i praksis en form for rotasjon av credentials?

**Comment by Kyrremann** [comment]
Går for en løsning som roterer passordet for en app, kaller den `nais postgres password rotate $app`. Denne vil da endre Postgres-brukeren og k8s secreten.
