### ISSUE TITLE
Støtte for Kotlin/gradle?

### ISSUE THREAD

**Issue by lhartvik** [nais/cli#203]
Når man kjører nais-kommandoen 
nais start --appname <my-app> --teamname <my-team> --appListenPort 8000
og man har generert et kotlin-prosjekt får man først feilmelding om at man mangler pom.xml eller tilsvarende. Hvis man toucher pom.xml og kjører på nytt får man yaml-filer som ikke passer helt med gradle og kotlin.

Forventet resultat: Det genereres oppsett som gjør at man kan kjøre kotlin-applikasjon på nais.
(Man kan sikkert snik-kikke på https://github.com/navikt/sokos-ktor-template .)

**Comment by jksolbakken** [comment]
De aller fleste teamene i NAV bygger Kotlin-appene sine med Maven eller Gradle, og `nais start` støtter begge disse. Hvis prosjektet (katalogen) inneholder en `pom.xml` eller en `build.gradle(.kts)` vil det genereres opplegg for å bygge vha hhv Maven og Gradle. Disse kan kjøres med et nærmest uendelig antall kombinasjoner av parametre og plugins, og det er umulig å skulle tilby støtte for alle disse variasjonene. Yaml-en som genereres er derfor ment som et generelt utgangspunkt som du kan tilpasse til dine behov.

**Comment by mortenlj** [comment]
Jeg tenker at uansett så er dette en feature request som hører hjemme på https://github.com/nais/start.nais.io
