### ISSUE TITLE
Kubeconfig: onprem cluster included without `--include-onprem` flag

### ISSUE THREAD

**Issue by thokra-nav** [nais/cli#269]
When running `nais kubeconfig`, onprem clusters are included, but without the user defined. 

Can we just stop having the `--include-onprem` flag?

**Comment by thokra-nav** [comment]
Small ping @Kyrremann

**Comment by Kyrremann** [comment]
Det at clusterne ble lagt til var bare forenkling av koden, så det kun var users-biten av koden som trengte å forholde seg til det. Så klart dumt at de dukker opp når man lister opp clusters. Dårlig testing fra min side.

Tanken med flagget var å skape mindre støy for de som har kommet seg helt til skyen.

**Comment by thokra-nav** [comment]
Okei, tenker at vi bør enten oppdatere dokumentasjonen med info (og ikke inkludere onprem clustre uten flagget) eller bare ta med onprem uansett. (så kan jo de som ønsker det slette onprem fra sine filer om man vil).

Kan godt gjøre det, men usikker på hvilken løsning :)

**Comment by jhrv** [comment]
Seeing as `nais cli` is used across other tenants as well, I'd vote for either removing the flag all together, i.e. you always get all clusters for the tenant regardless of where they reside. Alternatively, that you can exclude clusters in a generic manner. E.g.  `--exclude=dev-fss,prod-fss`
