### ISSUE TITLE
Telemetri i Nais-cli

### ISSUE THREAD

**Issue by Kyrremann** [nais/cli#423]
# Beskrivelse / Essensen

Vi har ingen oversikt over hva slags tjenester som blir brukt i Nais-cli. Det hadde vært interessant å hatt metrikker på bruk.
Dette kan gi oss innsikt i hva vi for eksempel kan fjerne.

Ved å samle inn denne informasjonen så kan vi:
- se om folk får mye feilmeldinger
- hvilke features og argumenter blir brukt
- er det features som blir brukt i rekkefølge

# Investeringsvilje

< 1 uke

# Mulig løsning i grove trekk

Per feature i Nais-cli så logger vi:
- feature
- argumenter
- feil/errors (interessant å se hvor mange feil brukerne får)

Alt dette kan vi sende til Amplitude.

Er også etterlyst mulighet til å kunne slippe telemetri, og da kan det være fornuftig å ikke lage vår egen greie.
https://consoledonottrack.com/

# Ikke-mål

Bytte cli-bibliotek.

# Eventuell annen relevant informasjon

Eksempel på hvordan Go-cli viser frem hva data de får: https://telemetry.go.dev/

# Shapers
- Kyrre Havik

**Comment by kimtore** [comment]
Sikkert nyttig med telemetri fra CLI, men er det virkelig verdt alle de personverns-issuene slik drar med seg? Ønsker vi å være med på denne antitrenden?

**Comment by Kyrremann** [comment]
Vi gjør jo tilsvarende i nais/deploy og i Console, så ser ikke at CLI er noe verre.

**Comment by Reasonable-Solutions** [comment]
marking as done as theres grafana and metrics now
